# Generated by Django 4.2.8 on 2024-01-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_price', models.CharField(max_length=15)),
                ('car_discription', models.TextField()),
                ('quentities', models.IntegerField()),
                ('car_image', models.ImageField(upload_to='cars/media/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brands')),
            ],
        ),
    ]
