# Generated by Django 4.2.8 on 2024-01-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/media/post/'),
        ),
    ]
