# Generated by Django 4.2.8 on 2024-01-17 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brands_slug'),
        ('cars', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brands'),
        ),
    ]
