# Generated by Django 4.2.8 on 2024-01-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_comment_email_alter_comment_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='brand',
        ),
        migrations.AddField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cars.cars'),
            preserve_default=False,
        ),
    ]
